# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "distribute app to firebase app distribution"
  lane :distribute do
    sh "flutter clean" 
    sh "flutter build apk --release"
    firebase_app_distribution(
      app: "1:150985216637:android:8fb20c90cac41ea2775714",
      firebase_cli_token:  ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "anassef798@gmail.com, moh.ghazal.saleh@gmail.com",
      release_notes: "New release",
    )
  end
 
end
